from .abono import *
from .administrador import *
from .cesion_abono import *
from .clasificacion import *
from .compra import *
from .competicion import *
from .equipo import *
from .jugador import *
from .noticia import *
from .partido import *
from .patrocinador import *
from .pedido import *
from .pedido_producto import *
from .post_foro import *
from .predice import *
from .producto import *
from .socio import *
from .socio_abono import *
from .usuario import *
